version: "3.8"

services:
  xopat-php:
    build:
      context: ../../
      dockerfile: docker/php/Dockerfile
      target: viewer-dev
    ports:
      - "9000:8000"
    volumes:
     - ../../:/var/www/html/xopat:ro
    ## You can set-up xopat directly using env, but remember to prefix $ --> $$ to avoid issues
    environment:
      XOPAT_ENV: |
        {
          "core": {
            "gateway": "https://xopat.readthedocs.io",
            "active_client": "localhost",
            "client": {
              "localhost": {
                "domain": "http://localhost:9000",
                "path": "/",
                "image_group_server": "http://localhost:9002",
                "image_group_protocol": "`$${path}/v3/batch/info?slides=$${data}`",
                "data_group_server": "http://localhost:9002",
                "data_group_protocol": "`$${path}/v3/batch/info?slides=$${data.join(\",\")}`",
                "headers": {},
                "js_cookie_expire": 365,
                "js_cookie_path": "/",
                "js_cookie_same_site": "",
                "js_cookie_secure": "",
                "secureMode": false,
              }
            },
            "setup": {
              "locale": "en",
              "customBlending": false,
              "debugMode": false,
              "webglDebugMode": false,
            },
            "openSeadragonPrefix": "https://cdn.jsdelivr.net/npm/openseadragon@4.1.1/build/openseadragon/",
            "openSeadragon": "openseadragon.min.js"
          },
          "plugins": {
          },
          "modules": {
            "empaia-wsi-tile-source": {
              "permaLoad": true
            }
          }
        }

